spring:
    mvc:
        view:
            prefix: /WEB-INF/jsp/
            suffix: .jsp
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:tsetdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        username: sa
        password:
        schema: classpath:schema-h2.sql
        initialize: true
        platform: h2
    jpa:
        database: h2
        hibernate:
            ddl-auto: create
        generate-ddl: true
    h2:
        console:
            enabled: true
            path: /h2-console

server:
  port: 9001